config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get "/blog_posts/new", to: "blog_posts#new", as: :new_blog_post
  get "/blog_posts/:id", to: "blog_posts#show", as: :blog_post
  post "/blog_posts", to: "blog_posts#create", as: :blog_posts
  post "/blog_posts/:id/feedback", to: "feedback#create", as: :feedbacks
  # Defines the root path route ("/")
  root "blog_posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord
    validates :title, presence: true
    validates :body, presence: true
    validates :author_name, presence: true
    validates :author_email, presence: true
    has_many :feedback
end

app/models/feedback.rb
class Feedback < ApplicationRecord
  belongs_to :blog_post
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
    def index
        @blog_posts = BlogPost.all
    end

    def new
        @blog_post = BlogPost.new
    end

    def show
        @blog_posts = BlogPost.find(params[:id])
    rescue ActiveRecord::RecordNotFound
        redirect_to root_path
    end

    def create
        @blog_post = BlogPost.new(blog_post_params)
        if @blog_post.save
            redirect_to @blog_post
        else
            render :new, status: :unprocessable_entity
        end
    end

    private

    def blog_post_params
        params.require(:blog_post).permit(:title, :body, :author_name, :author_email)
    end
end

app/controllers/feedback_controller.rb
class FeedbackController < ApplicationController
    def create
        @blog_post = BlogPost.find(params[:id])
        
        if @blog_post.author_name != nil && @blog_post.author_email != nil
            NotifierMailer.with(user: @blog_post).new_feedback(@blog_post.author_email).deliver_now
        else
            NotifierMailer.new_feedback_no_email.deliver_now
        end
        @feedback = Feedback.new(feedback_params)
        if @feedback.save
            redirect_to blog_posts_path()
        else
            redirect_to abort feedback_params.inspect
        end
    end

    private

    def feedback_params
        params.require(:feedback).permit(:user, :content).merge(blog_post_id: params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/feedback_helper.rb
module FeedbackHelper
end

app/views/blog_posts/index.html.erb
<h1>
    Blog Site
</h1>
<h2>
    Create new <a href=<%= new_blog_post_path() %>>here</a>
</h2>

<% @blog_posts.each do |blog_post| %>
<div>
    <h2>Title: <%= link_to blog_post.title, blog_post_path(blog_post.id) %></h2>
    <p>Body: <%= blog_post.body %></p>
    <p>Author: <%= blog_post.author_name %></p>
    <p>Email: <%= blog_post.author_email %></p>
</div>
<%end%>

app/views/blog_posts/new.html.erb
<h1>New Blog Post</h1>

<%= form_with model: @blog_post do |form| %>
    <% form.object.errors.full_messages.each do |message|%>
        <div><%= message %>
        <% end %>
    
    <div>
        <%= form.label :title %>
        <%= form.text_field :title %>
    </div>
    <div>
        <%= form.label :body %>
        <%= form.text_area :body %>
    </div>
    <div>
        <%= form.label :author_name %>
        <%= form.text_field :author_name %>
    </div>
    <div>
        <%= form.label :author_email %>
        <%= form.email_field :author_email %>
    </div>
    
    <%= form.button %>
<% end %>

app/views/blog_posts/show.html.erb
<h2>
    <a href="/">Back</a>
</h2>
<h1>Title: <%= @blog_posts.title %></h1>
<p>Body: <%= @blog_posts.body %></p>
<p>Author: <%= @blog_posts.author_name %></p>
<p>Email: <%= @blog_posts.author_email %></p>

<h2>Feedback</h2>
<%= render @blog_posts.feedback %>
<%= render partial: 'feedbacks/form' , locals: { post: @blog_posts }%>

app/views/feedbacks/_feedback.html.erb
<article>
    <p><%= feedback.content %></p>
    <small>by: <%= feedback.user %></small>
</article>

app/views/feedbacks/_form.html.erb
<form action=<%= feedbacks_path(post) %> method="post">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token  %>">
    <p>User</p> <input type="text" name="feedback[user]" value="">
    <p>Content</p> <textarea name="feedback[content]" rows="6" cols="20"></textarea>
    <input type="submit" value="Submit">
</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>